# Generated by Django 3.2.7 on 2021-09-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_created=True)),
                ('school', models.CharField(max_length=255, unique=True)),
                ('course_code', models.CharField(max_length=255, unique=True)),
                ('rating', models.IntegerField(default=0)),
                ('notes', models.FileField(upload_to='')),
            ],
        ),
    ]
